version: "3"
services:
  kaggle:
    image: gcr.io/kaggle-gpu-images/python:latest
    container_name: sea-image-converter
    volumes:
      - ./:/kaggle/working
      - ./sea_images:/kaggle/input
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    shm_size: '24gb'
