version: "3"
services:
  app:
    image: sea-image-converter:v1
    volumes:
      - ../:/app
      - ../../../datasets:/datasets
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    shm_size: '16gb'

