#-----------GENERAL-----------
project: great-barrier-reef
name: sea-iamge-converter
debug: false
resume: null

#-------------ENV-------------
# root_dir: /app
root_dir: /Users/so/workspace/sea-image-converter
# dataset_dir: /datasets
dataset_dir: /Users/so/datasets/sea_images/Paired
save_dir: ${root_dir}/output/${project}/${name}
accelerator: auto
devices: -1

#-------------DATA-------------
input_shape: [3, 256, 144]
batch_size: 16
num_workers: 8
prefetch_factor: 5
train_data:
  name: sea
  dataroot_IN: ${dataset_dir}/underwater_dark/trainA, ${dataset_dir}/underwater_imagenet/trainA, ${dataset_dir}/underwater_scenes/trainA
  dataroot_GT: ${dataset_dir}/underwater_dark/trainB, ${dataset_dir}/underwater_imagenet/trainB, ${dataset_dir}/underwater_scenes/trainB

val_data:
  name: sea  # pickup last 100 images
  dataroot_IN: ${dataset_dir}/underwater_dark/validA, ${dataset_dir}/underwater_imagenet/validA, ${dataset_dir}/underwater_scenes/validA
  dataroot_GT: ${dataset_dir}/underwater_dark/validB, ${dataset_dir}/underwater_imagenet/validB, ${dataset_dir}/underwater_scenes/validB

#-------------MODEL-------------
model:
  metric: val_loss
  mode: min
  rrdb:
    nf: 64
    nb: 23
    gc: 32

#------------TRAINER------------
trainer:
  manual_seed: 10
  resume: null

  args:
    max_epochs: 1000
    check_val_every_n_epoch: 20
    devices: ${devices}
    accelerator: ${accelerator}
    auto_select_gpus: true
    progress_bar_refresh_rate: 1
    accumulate_grad_batches: 4
    # stochastic_weight_avg: true
    # auto_scale_batch_size: binsearch
    # auto_lr_find: true
    gradient_clip_val: 0.5
    limit_train_batches: 1e8    # for debug
    limit_val_batches: 1e8      # for debug
    benchmark: true
    deterministic: false
    amp_backend: apex
    amp_level: O1   # mixed precision
  
  optimizer:
    lr: 5e-4
    b1: 0.5
    b2: 0.99
  
  scheduler:
    milestones: [0.5, 0.75, 0.9, 0.95]
    gamma: 0.5
